//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string CardholderName { get; set; }
        public string Number { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int IdCardBrand { get; set; }
        public string Password { get; set; }
        public int IdCardType { get; set; }
        public bool HasPassword { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> LimitUsed { get; set; }
        public bool Blocked { get; set; }
        public int Attempts { get; set; }
    
        public virtual CardBrand CardBrand { get; set; }
        public virtual CardType CardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
