//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int IdTransactionType { get; set; }
        public int IdCard { get; set; }
        public int Number { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.Guid ClientCode { get; set; }
        public Nullable<int> TransactionReturn { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
